# Generated by Django 3.2.6 on 2021-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210903_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
