# Generated by Django 3.2.6 on 2021-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210905_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Screen_Shot_2021-08-07_at_1.22.31_PM_wVXWw8N.png', null=True, upload_to=''),
        ),
    ]
