# Generated by Django 3.2.6 on 2021-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='due_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
