# Generated by Django 3.2.6 on 2021-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0003_alter_todolist_due_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='due_created',
        ),
        migrations.AddField(
            model_name='todolist',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
