# Generated by Django 3.2.6 on 2021-09-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0005_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(blank=True),
        ),
    ]
