# Generated by Django 3.2.6 on 2021-09-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0006_alter_item_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='Created',
        ),
    ]
